# Generated by Django 4.0.4 on 2023-12-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('tva', models.IntegerField(default=18)),
                ('products', models.ManyToManyField(blank=True, null=True, to='products.product')),
            ],
        ),
    ]
