# Generated by Django 4.0.4 on 2023-12-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Solded')], default='P', max_length=1),
        ),
    ]
