# Generated by Django 4.0.4 on 2023-12-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
        ('facturation', '0003_alter_facturation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturation',
            name='products',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='facturation',
            name='products_items',
            field=models.ManyToManyField(blank=True, to='facturation.cartitem'),
        ),
    ]
