# Generated by Django 4.0.4 on 2023-12-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productitems', '0001_initial'),
        ('facturation', '0005_remove_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='products_items',
            field=models.ManyToManyField(blank=True, to='productitems.productitem'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
