# Generated by Django 4.0.4 on 2023-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='the_cost',
            field=models.IntegerField(default=0),
        ),
    ]
